# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
