# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='lang',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='answers',
            name='track',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
