# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_cfprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfprogress',
            name='question2',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cfprogress',
            name='question3',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cfprogress',
            name='question4',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
